<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Logger" Id="{3f21913f-9ad4-4393-888f-56e18dd3bff9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_Logger EXTENDS FB_ManagerAdapter
VAR
	_pLogManager				: POINTER TO FB_LogManager;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Init" Id="{574d614e-7b92-4a97-9c1b-d4431dcbff33}">
      <Declaration><![CDATA[METHOD PUBLIC Init : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Init := TRUE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>